# Generated by Django 5.2.7 on 2025-12-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_reserva',
            field=models.BooleanField(default=False, verbose_name='Es Reserva'),
        ),
    ]
